[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat.*", group = "<!-- 0 -->:rocket: New Features"},
    { message = "^fix.*", group = "<!-- 1 -->:bug: Bug Fixes"},
    { message = "^doc.*", group = "<!-- 4 -->:memo: Documentation"},
    { message = "^perf.*", group = "<!-- 2 -->:zap: Performance"},
    { message = "^refactor.*", group = "<!-- 6 -->:recycle: Refactor"},
    { message = "^style.*", group = "<!-- 7 -->:lipstick: Styling"},
    { message = "^test.*", group = "<!-- 5 -->:test_tube: Testing"},
    { message = "^chore.*", group = "<!-- 8 -->:gear: Miscellaneous"},
    { message = ".*deprecated", body = ".*deprecated", group = "<!-- 3 -->:wastebasket: Deprecation" },
    { message = "^revert.*", skip = true }
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = 'v[0-9]+\.[0-9]+\.[0-9]+.*'

skip_tags = 'v[0-9]+\.[0-9]+\.[0-9]+-.*'
topo_order = false
sort_commits = "oldest"
link_parsers = [
    { pattern = "#(\\d+)", href = "https://github.com/pedregon/scaffold/issues/$1"},
]

[changelog]
header = "Changelog"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }}
    {% endfor %}
{% endfor %}
"""
trim = true
footer = "<!-- generated by git-cliff -->"